# Generated by Django 4.1.5 on 2023-03-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=13)),
                ('Profile_pic', models.FileField(upload_to='images/')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
