# Generated by Django 4.1.5 on 2023-03-31 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='users',
            table='peoples',
        ),
    ]
