# Generated by Django 4.1.5 on 2023-03-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Peoples',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=13)),
                ('profile_pic', models.FileField(upload_to='images/')),
            ],
            options={
                'db_table': 'peoples',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
